### ISSUE TITLE
WebStrom 问题

### ISSUE THREAD

**Issue by tangxve** [tangxve/notes#16]
# WebStrom

## React 支持 CSS Modules 联想

css 文件：
```css
.App {
  background-color: rgba(0, 0, 0, 0.08);
}

.app-header {
  background-color: white !important;
}

.AppLogo {
  height: 60px;
  width: 60px;
  float: left;
}
```

jsx 文件：

编辑只能联想到驼峰类型，不能真正匹配到

![img](https://github.com/tangxve/notes/assets/20086376/8f633ca8-d4b9-4caa-a239-9135dd982512)

解决方法：下载 React CSS Modules 插件

`设置 => 插件 => 搜索 React CSS Modules 下载使用`

插件地址：[React CSS Modules](https://plugins.jetbrains.com/plugin/9275-react-css-modules)
